### ISSUE TITLE
Cannot use Mongoose Operators when using find or findOne

### ISSUE THREAD

**Issue by rubencosta13** [wheresvic/mongoose-field-encryption#108]
Greetings!

I'm using mongoose-field-encryption to encrypt specific fields on a model... However, I need to find  data with a mongoose operator: ``$in:`` Which refuses to work with mongoose-field-encryption!

Here are the code snippets I'm using:

Create the users:
```js
const createUser = new User({
    name: "Maria", 
    attributes: [
      "Self Taught SWE",
      "Developer"
    ]
  })
const createBogusUser = new User({
    name: "John", 
    attributes: [
      "Self Taught SWE",
    ]
  })
await createUser.save();
await createBogusUser.save()
```

My goal is to find all the users that have the attribute "Developer", which, without mongoose-field-encryption can be done as follows:

Source: [Docs](https://www.mongodb.com/docs/manual/reference/operator/query/in/)
```js
await User.find({ attributes: { $in: ["Developer"] });
```

**However** if I try to run the same query, on a model that has mongoose-field-encryption, it will return all the documents, even though only the user "Maria" has the developer attribute... 

Is there any way to fix this?

**Comment by rubencosta13** [comment]
@wheresvic Any updates here? 

Also my populates arent working... 

here's a sample of my model: 

```js
const userModel = new mongoose.Schema({
  user: {
    type: String,
    required: true
  },
  userAttributes: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'UserAttributes',
    },
  ],
});


const userAttributes = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  attributes: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'UserAttributes',
    },
  ],
  status: {
    type: Boolean,
    required: true
  }
});

const attributes = new Attributes({
  name: 'Developer',
  attributes: [
    'Developer',
    'SWE',
    'some random entry'
  ],
  status: true
});

const user = new User({
  user: "John",
  attributes: attributes._id
});

attributes.save();
user.save();
```

if I try to populate the attributes on the user, it just returns me null, on the whole query

**Comment by ThamerAlluqmani** [comment]
Hi @rubencosta13 , I'm facing same issue. Did you solve it ?
