### ISSUE TITLE
Support findOneAndUpdate

### ISSUE THREAD

**Issue by hotohoto** [wheresvic/mongoose-field-encryption#14]
I found it was not encrypted when I updated the data using `findOneAndUpdate`. Please support it.

Additionally, there seems to be other APIs to update data, and they need to be covered by this library.

http://mongoosejs.com/docs/middleware.html

**Comment by victorparmar** [comment]
Hi!

Thanks for taking the time to open and issue. What versions of mongoose, Node.js and MongoDb are you using?

**Comment by vinczedani** [comment]
#20 should add the required hook for findOneAndUpdate
