### ISSUE TITLE
TypeError: saltGenerator is not a function or wrong usage please give full working examples

### ISSUE THREAD

**Issue by martyh888** [wheresvic/mongoose-field-encryption#29]
I have tried following the documentation and I cannot get this to work

`mongoose.connect('mongodb://localhost:27017/csvfilereader', {useNewUrlParser: true});
var conn = mongoose.connection;

let Schema = mongoose.Schema;

let postSchema = new Schema({
  title: String,
  message: String
});
Post = mongoose.model('Post', postSchema);

const fieldEncryption = require('mongoose-field-encryption')
const encrypted = fieldEncryption.encrypt('some text', 'secret');

postSchema.plugin(mongooseFieldEncryption, {fields: ['message'], secret: 'some secret key'});

post = new Post ({ title: encrypted, message: 'hello all' });
post.save(function(err){ // encrypted when sent to the database
                        // decrypted in the callback
  console.log(post.title); // Joe
  console.log(post.message); // 42
  console.log(post._ct); // undefined
});`

I have tried multiple variations and haven found anywhere on the sites or in other places on how to get it all working. The closest I cam was then bringing up the following error

const iv = saltGeneratorWrapper(saltGenerator(secret));
TypeError: saltGenerator is not a function

On another note, there is a few code typos 
"plugin(mongooseFieldEncryption" was missing the r in Encryption
const encrypted = fieldEncryption.encrypt('some text', 'secret')); there is an extra ) on the end of this line

**Comment by wheresvic** [comment]
Hello and sorry for the delay in responding,

Please try the following:

```
mongoose.connect("mongodb://localhost:27017/csvfilereader", { useNewUrlParser: true });
// var conn = mongoose.connection;

let Schema = mongoose.Schema;

let postSchema = new Schema({
  title: String,
  message: String
});

Post = mongoose.model("Post", postSchema);

const mongooseFieldEncryption = require("../lib/mongoose-field-encryption").fieldEncryption;
// the line below is unnecessary, the plugin will encrypt the document automatically
// const encrypted = fieldEncryptionPlugin.encrypt("some text", "secret");

postSchema.plugin(mongooseFieldEncryption, { fields: ["message"], secret: "some secret key" });
post = new Post({ title: "some text", message: "hello all" });
post.save(function(err) {
  // encrypted when sent to the database
  // decrypted in the callback
  console.log(post.title); // some text
  console.log(post.message); // hello all
  console.log(post._ct); // undefined
});
```

As you can see, you only needed to set the encryption plugin, you do not need to actually encrypt it manually. 

I will also update the documentation to clearly reflect this, let me know if you have any other issues.
