### ISSUE TITLE
Searching Encrypted fields

### ISSUE THREAD

**Issue by martyh888** [wheresvic/mongoose-field-encryption#31]
How do I do a find on encrypted fields? Find works ok on non-encrypted fields and decrypts the contents of the encrypted fields but doing a direct search on the encrypted filed doesn't work. Also, the search will be a like statement eg 'SMI%' to return SMITH for example

**Comment by wheresvic** [comment]
Hello,

Encryption is a one-way street unfortunately so the idea is that once you encrypt it you have no idea of
what the original contents were. However, what `mongoose-field-encryption` does provide is the ability to search for the _exact_ string if you know it. Cases include names, sex, age, etc.

If you're looking to do wildcard searches then I can recommend the following:
- keep a single collection with personable identifiable information (PII) and encrypt everything in it, call it `records`.
- keep a collection which has a document per streetname and in this document is a list of ids pointing to the documentIds of the people in the `records` collection.
- similarly keep a collection for each field that you'd like to do partial matching on.

This does increase the complexity of adding and retrieving documents (think transactions where you add to the records collection but fail to update the streetname collection) but will at the very least give you the
ability to do what you are looking to do.

Another option would be to make classes of search criteria, e.g. the string "si" points to all streetnames with the phrase "si" in it. You can add these classes as extra fields to the document and then
leave them unencrypted. This provides lower security but probably easier to implement.

I have updated the `mongoose-field-encryption` documentation to provide an example on how to do a search for an _exact_ string match. I hope that what I provided helps you!

Thanks for using the plugin,

**Comment by wheresvic** [comment]
https://github.com/wheresvic/mongoose-field-encryption#search-over-encrypted-fields
