### ISSUE TITLE
Not working with Aggregate Query

### ISSUE THREAD

**Issue by eldhoseelias** [wheresvic/mongoose-field-encryption#32]
Its not working with aggregate query

**Comment by wheresvic** [comment]
Hello,

Could you please provide an example of what is not working exactly? 

Using the field-encryption plugin will encrypt the fields which means that running aggregate queries on them will not make any sense.

If you require aggregate data, I would suggest that you create another data structure / collection and aggregate the data at the time of insertion or better yet, do it as part of a scheduled process.

Cheers,

**Comment by bakkostas** [comment]
I have the same error
Is there any answer?

**Comment by wheresvic** [comment]
@bakkostas 

Can you please provide an example of what is not working?

**Comment by bakkostas** [comment]
I have two model Account and My_schema

`

var account_schema = new mongoose.Schema({
    name: { type: String },
    surname: { type: String },
    email: { type: String, required: true, index: true, unique: true },
    password: { type: String, required: true },
    roles: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Roles' }],
    club: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Clubs' }],
    operator: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Operators' }],
    cityAdmin: [{ type: mongoose.Schema.Types.ObjectId, ref: 'CityAdmin' }],
    subscriber: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Amea' }],
    active: { type: Boolean, default: false },
    uuid: { type: String, default: "1" },
    created: { type: Date },
    last_login: { type: Date },
    acceptPrivacy: { type: Array }
});
`

`

var My_schema = new mongoose.Schema({
    name: { type: String },
    surname: { type: String },
    email: {
        value: { type: String, default: '' },
        active: { type: Number, default: 0 }
    },
    phoneNumber: {
        value: { type: String, default: '' },
        active: { type: Number, default: 0 }
    },
    loc: {
        type: { type: String },
        coordinates: { type:[]}
    },
    region: {
        administrative: { type: String }, municipality: { type: String }
    },
    floor: { type: Number },
    owner: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Account' }],
    club: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Clubs' }],
    birthday: { type: Date },
    created: { type: Date, default: new Date() },
    updated: { type: Date },
    address: { type: String },
    status: {type:String} //1. pending 2.cancelled 3.active
});

My_schema .plugin(mongooseFieldEncryption, { fields: ["surname"], secret: "Encryption4all" });

My_schema .index({ 'loc.coordinates': '2dsphere' });

`
I have an endpoint with aggregation like that

`

Account.find({ "uuid": req.headers.token }, function (err1, resp1) {
            if (err1) console.log(err1);

            if (resp1.length > 0) {
               

                    My_schema.aggregate([
                        {
                            $geoNear: {
                                near: req.body.loc,
                                distanceField: "dist.calculated",
                                maxDistance: parseInt(req.body.maxdistance),
                                spherical: true
                            }
                        }
                    ], (err, data) => {
                        if (err) {
                            throw err;
                            console.log(err);
                            res.status(400).send({ "message": "BAD_REQUEST" });
                        } else {
                            /*var sss = fieldEncryption.stripEncryptionFieldMarkers(data[0].surname, "Encryption4all");
                            console.log(sss);*/
                            
                            console.log(data[0].surname);
                            res.status(200).send(data);
                        }
                    });
                } else {
                    res.status(403).send({ "text": "Forbidden" });
                }
            } else {
                res.status(403).send({ "text": "Forbidden" });
            }
        }).populate("operator").populate("roles").populate({ path: "subscriber", model: "Amea" });//
}

`
The response give not decrypt the surname field.

**Comment by wheresvic** [comment]
Hello,

You can use the `decryptFieldsSync()` method to decrypt the surname manually. 

Alternatively you can also use the decrypt method to manually decrypt the surname and store it:

```
/*
var sss = fieldEncryption.stripEncryptionFieldMarkers(data[0].surname, "Encryption4all");
console.log(sss);
*/

console.log(fieldEncryption.decrypt(data[0].surname, 'secret')));
console.log(data[0].surname);
res.status(200).send(data);
```

Hopefully this helps,

**Comment by bakkostas** [comment]
Thank you in advance!

I have a problem with the crypto hash!

I use the above code

let key = crypto.createHash('sha256').update(String("Encryption4all")).digest('hex').substr(0, 32);
console.log(fieldEncryption.decrypt(data[0].surname, key));

Now all works fine.

Thank you!

**Comment by wheresvic** [comment]
@eldhoseelias let me know if you need further help, thanks!

**Comment by bakkostas** [comment]
no the code works fine!

thanks!

**Comment by adasarpan404** [comment]
how to do it for large files
