### ISSUE TITLE
Bug in example code

### ISSUE THREAD

**Issue by ronaldlong46** [wheresvic/mongoose-field-encryption#35]
Line 51 of README.md is:
`PostSchema.plugin(mongooseFieldEncyption, { fields: ["message", "references"], secret: "some secret key" });
`

It should be:
`PostSchema.plugin(mongooseFieldEncryption, { fields: ["message", "references"], secret: "some secret key" });
`

**Comment by wheresvic** [comment]
Whoops - thanks for pointing that out! Fixed now :)
