### ISSUE TITLE
I cannot make it work when updating a decrypted field

### ISSUE THREAD

**Issue by peelmicro** [wheresvic/mongoose-field-encryption#38]
I've been able to make the plugin work when a new document is created. It stores the information encrypted in the database and it decrypts it properly when using **find**, **findOne** and **findById**.

The problem is when I try to update an encrypted value. I've tried several situations:

- Using **update**, even it is deprecated, adding the **__enc_fieldname: false** or not adding it.
- Using **findOneAndUpdate**, adding the **__enc_fieldname: false** or not adding it.
- Using **findByIdAndUpdate**, adding the **__enc_fieldname: false** or not adding it. I think this is normal because it doesn't seem to be supported yet. This is the method that I use by default, but, if it worked I could change to use the **findOneAndUpdate** one.

In all the cases it doesn't encrypt the value again and the  **__enc_fieldname** field with **true** is completely removed. 

If I add the **__enc_fieldname: false**, it creates that **__enc_fieldname** with the **false** value, but it doesn't encrypt it. If I run it again, the **__enc_fieldname** is removed but it is not updated encrypted either.

Could you please let me know what I'm supposed to do to make it work? Thanks in advance.

Juan Pablo Perez

**Comment by wheresvic** [comment]
Hi,

I really apologize for the delay in responding to you - somehow I missed this notification! Anyways, unfortunately according to the mongoose docs here: https://mongoosejs.com/docs/middleware.html#notes, `findOneAndUpdate()` is not supported for middleware. 

Thus, you need to retrieve the document, make your updates and then save it again in order for the encryption plugin to do its job. Hope this helps!

**Comment by wheresvic** [comment]
Closing this issue now.
