### ISSUE TITLE
Deprecation issue

### ISSUE THREAD

**Issue by rogeryeosgit** [wheresvic/mongoose-field-encryption#42]
Just stumbled onto this nice tool. Works quite straight forward. Thanks. 👍 

Just a question.. Is the "collection.update is deprecated..." warning anything to worry about? and is there a reason not to use updateOne or updateMany instead?

Was reading the code and figured there must be some considerations about this since it has been left in or maybe I'm missing something in terms of Mongoose versions.

Using
"mongoose": "^5.10.6"

**Comment by wheresvic** [comment]
Hi @rogeryeosgit,

Sorry for the delay in getting back to you on this. Essentially, the `update` hook is there for backwards compatibility. However, the latest release `3.1.0` also includes support for the `updateOne` function. I hope that this helps.

Please do test this method out thoroughly and let me know if you see any issues.

Cheers,

**Comment by wheresvic** [comment]
Closing now.
