### ISSUE TITLE
decryption of nested fields not happening for "findbyid", "find" & "findOne" queries

### ISSUE THREAD

**Issue by Joypaul11** [wheresvic/mongoose-field-encryption#45]
When making above queries, decryption of nested fields is not happening automatically.

**Comment by wheresvic** [comment]
Thanks for filing the issue, could you please provide more detail regarding your implementation?

Note that `mongoose-field-encryption` does not support encryption of nested fields specifically. You might need to make a sub-document schema and add the plugin to that. If you could provide an example perhaps we could try and help,

Thanks!

**Comment by wheresvic** [comment]
Closing this issue now.
