### ISSUE TITLE
Querying gives decrypted data but calling fieldEncryption.decrypt causes error - error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by amitistyping** [wheresvic/mongoose-field-encryption#52]
Steps to Reproduce:

1. Encrypt this way - mySchema.plugin(mongooseFieldEncryption, { fields: ["message", "sender", "receiver"], secret: "AsEAabUmaIK3C8FTpuzPHrZJhvhiS8zY" });
2. Decrypt this way -  fieldEncryption.decrypt(messageObj.messageData.receiver, 'AsEAabUmaIK3C8FTpuzPHrZJhvhiS8zY') 
3. Causes below error - 

![image](https://user-images.githubusercontent.com/25412894/103351179-5bdc2200-4ac8-11eb-9697-d57019139cad.png)
![image](https://user-images.githubusercontent.com/25412894/103351185-64345d00-4ac8-11eb-9593-1735619b0a83.png)

However, when I used find queries with Mongoose, I get decrypted data just fine.

**Comment by lazzyn** [comment]
Also, I was getting invalid key error earlier when using fieldEncryption.decrypt - so I had to change my key length to 32 characters as was suggested somewhere on StackOverFlow.

**Comment by wheresvic** [comment]
Hi @lazzyn ,

You need to make sure that `messageObj.messageData.receiver` is actually the encrypted value. Can you print out that field before calling the function to decrypt?

Finally note that if the encrypted field is an object the data is put under `__enc_fieldname_d` (replace fieldName with the actual fieldname).

**Comment by wheresvic** [comment]
Closing now.
