### ISSUE TITLE
I have problem with findOneAndUpdate mongoose function and the update at the nested fields

### ISSUE THREAD

**Issue by bakkostas** [wheresvic/mongoose-field-encryption#55]
I am running mongoDB 4.0.9 , nodejs 10.15.3 mongoose 5.5.1 and mongoose_encryption_field 4.0.1.

The problem is that all the nested fields updated as plain text with findOneandUpdate function.

For example the model is:

`var emailSchema = new mongoose.Schema({
    value: { type: String, default: '' },
    active: { type: Number, default: 0 }
});

emailSchema.plugin(mongooseFieldEncryption, { fields: ["value"], secret: "Encryption4all" });

var phoneNumberSchema = new mongoose.Schema({
    value: { type: String, default: '' },
    active: { type: Number, default: 0 }
});

phoneNumberSchema.plugin(mongooseFieldEncryption, { fields: ["value"], secret: "Encryption4all" });

var caretakerSchema = new mongoose.Schema({
    carename: { type: String },
    caresurname: { type: String },
    careemail: { type: String },
    carephone: { type: String },
    caredescription: { type: String }
});

caretakerSchema.plugin(mongooseFieldEncryption, {
    fields: ["carename", "caresurname", "careemail","carephone"], secret: "Encryption4all" });

var amea_schema = new mongoose.Schema({
    name: { type: String },
    surname: { type: String },
    email: emailSchema,
    phoneNumber: phoneNumberSchema,
    loc: {
        type: { type: String },
        coordinates: { type:[]}
    },
    owner: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Account' }],
    caretaker: caretakerSchema
});

amea_schema.plugin(mongooseFieldEncryption, { fields: ["name", "surname"], secret: "Encryption4all" });`

As you see i have encrypted fields in root and nested (for example name, surname, phonenumber.value etc).

I don't understand what i am doing wrong.

I am waiting your response!

Thanks in advance.

**Comment by khalilmansouri** [comment]
Can you please share more details like the query and the erreur message you get?

**Comment by bakkostas** [comment]
Hi thanks for your response,

my query is :

`_MyModel.findOneAndUpdate({
                                    "_id": req.body._id
                                }, {
                                        $set: {
                                            "name": req.body.name,
                                            "surname": req.body.surname,
                                            "email": {
                                                "value": _ameaEmail,
                                                "active": 1
                                            },
                                            "phoneNumber": {
                                                "value": req.body.phoneNumber,
                                                "active": 1
                                            },
                                            "loc": req.body.loc,
                                            "owner": resp[0]._id,
                                            "caretaker": {
                                                "carename": req.body.carename,
                                                "caresurname": req.body.caresurname,
                                                "careemail": req.body.careemail,
                                                "carephone": req.body.carephone,
                                                "caredescription": req.body.caredescription,
                                            }                  
                                        }
                                    }, function (err, doc) {.........mycode...........});`

When i run that query the fields email.value, phoneNumber.value, caretaker.carename ,caretaker.caresurname, caretaker.careemail ,caretaker.carephone saved as plain text.

The name, surname fields saved as encrypted.

I don't have any error responce but the nested fields are saved not encrypted but as plain text.

Thanks in advance.

**Comment by wheresvic** [comment]
Hi @bakkostas 

Unfortunately the plugin does not execute on `findOneAndUpdate`, See mongoose documentation for query middleware here: https://mongoosejs.com/docs/middleware.html#notes

You will need to manually do a find - get the document, make your changes and then save it back again. 

There is support for `findOneAndUpdate` but it is pretty clunky - you need to manually set the encryption field marker as shown in the readme. However, I would highly recommend that you just find the document make your changes and save it.

Cheers,

**Comment by bakkostas** [comment]
Hi again,

Thanks for your response.

I use the solution that i describe here and all works fine.

In the model i use,  i change the last line that i wrote above `amea_schema.plugin(mongooseFieldEncryption, { fields: ["name", "surname"], secret: "Encryption4all" });` with the line as you see under.

`var emailSchema = new mongoose.Schema({
value: { type: String, default: '' },
active: { type: Number, default: 0 }
});

emailSchema.plugin(mongooseFieldEncryption, { fields: ["value"], secret: "Encryption4all" });

var phoneNumberSchema = new mongoose.Schema({
value: { type: String, default: '' },
active: { type: Number, default: 0 }
});

phoneNumberSchema.plugin(mongooseFieldEncryption, { fields: ["value"], secret: "Encryption4all" });

var caretakerSchema = new mongoose.Schema({
carename: { type: String },
caresurname: { type: String },
careemail: { type: String },
carephone: { type: String },
caredescription: { type: String }
});

caretakerSchema.plugin(mongooseFieldEncryption, {
fields: ["carename", "caresurname", "careemail","carephone"], secret: "Encryption4all" });

var amea_schema = new mongoose.Schema({
name: { type: String },
surname: { type: String },
email: emailSchema,
phoneNumber: phoneNumberSchema,
loc: {
type: { type: String },
coordinates: { type:[]}
},
owner: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Account' }],
caretaker: caretakerSchema
});

amea_schema.plugin(mongooseFieldEncryption, { fields: ["name", "surname", **"email.value", "phoneNumber.value", "caretaker.carename", "caretaker.caresurname", "caretaker.careemail", "caretaker.carephone"**], secret: "Encryption4all" });`

I put in the enctyption plugin all the fields and the nested and works fine. Now when i use the findOneadnUpdate works perfect and in the nested fields , for example caretaker nested field, create a structure in the collection:
__inc_caretaker{
carename: true, 
caresurname: true,
careemail: true,
carephone: true
}

Do you see any conflict?

Thanks you in advance.

Kostas

**Comment by wheresvic** [comment]
Hi @bakkostas 

If it works then thats good, I personally do not recommend relying on this feature too much as it is dependent on mongoose internals. I would recommend to do a `find` then make changes and then `save` it back.

It would be easier to maintain at any rate.

**Comment by wheresvic** [comment]
This issue has been resolved.
