### ISSUE TITLE
How to query encrypted nested field? 

### ISSUE THREAD

**Issue by Ayushk93** [wheresvic/mongoose-field-encryption#68]
Below is my schema:

`const UserExtraSchema = new mongoose.Schema({
  city: { type: String },
  country: { type: String },
  address: { type: String },
  postalCode: { type: String },
});

UserExtraSchema.plugin(mongooseFieldEncryption, {
  fields: ['city', "address"],
  secret: "Secret Key",
  saltGenerator: (secret) => secret.slice(0, 16),
});

export const UserSchema = new mongoose.Schema({
  name: String,
  email: String,
  age: Number,
  address: UserExtraSchema
}, { collection: 'users', versionKey: false });

UserSchema.plugin(mongooseFieldEncryption, 
  { 
    fields: ["name", "email", "address.city", "address.address"], 
    secret: "Secret Key",
    saltGenerator: (secret) => secret.slice(0, 16),
})`

And I want to perform search document based on nested encrypted field. Query for reference:

`const data = await this.userModel.findOne({ "address.city": <encrypted_string> }).exec();`

How I can achieve this?

**Comment by wheresvic** [comment]
Hi @Ayushk93 

So in this scenario what you would need to do is to actually create a Moogoose schema for the Address subdocument and then add the encryption plugin to address as well as the user document. Then you can do an `encryptSync()` on your search address document and run your query. 

See the test for an example: https://github.com/wheresvic/mongoose-field-encryption/blob/036917d580e0d43c28f3331d0025af439d6ee18c/test/test-basic-usage.js#L66

The piece you are missing is adding the encryption plugin to the subdocument.
