### ISSUE TITLE
Decrypt method uses secret directly, the mongoose hooks use a hash

### ISSUE THREAD

**Issue by wassil** [wheresvic/mongoose-field-encryption#71]
I've been struggling with `decrypt` method getting `error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt`.
Couple of people already reported issues like this.
The problem is that when you setup encryption on the fields, the library doesn't use the secret directly, but rather calculates a hash of the secret. https://github.com/wheresvic/mongoose-field-encryption/blob/master/lib/mongoose-field-encryption.js#L85

So when you call e.g. `schema.plugin(fieldEncryption, { fields: ['FIELD'], 'YOUR_SECRET'});` and later try to decrypt the field directly with `decrypt(object['FIELD'], 'YOUR_SECRET')` you get an error. What you actually need to do is:
```
const _hash = (secret) => crypto.createHash("sha256").update(secret).digest("hex").substring(0, 32);
decrypt(object['FIELD'], _hash('YOUR_SECRET');
```

I think this should be documented. Or even better, the public `encrypt`/`decrypt` methods should calculate the actual encryption secret the same way as the library does when encrypting /decrypting

**Comment by wheresvic** [comment]
@wassil the `decrypt` method is actually an internal method. The plugin does expose a static method `decryptFieldsSync` which is documented.

Does the static method not work for you?

**Comment by wassil** [comment]
`decrypt` is mentioned in the docs here: https://github.com/wheresvic/mongoose-field-encryption#searching

I only had a database dump, not actual mongoose object. I assume that `decryptFieldsSync` needs a mongoose object to work, that's why I chose `decrypt`

**Comment by wheresvic** [comment]
ok that's fair, I can add it to the README then, cheers!

**Comment by wheresvic** [comment]
This is now done, sorry for the delay!

**Comment by wheresvic** [comment]
Also added a test to verify behaviour :)
